### ISSUE TITLE
Trying to compile the clock ino file, and it's giving an error

### ISSUE THREAD

**Issue by devicemodder** [maarten-pennings/303WIFILC01#5]
on line 93, arduino IDE gives an  error: E:\Downloads\303WIFILC01-main\5-clock\nCLC\nCLC.ino: In function 'void setup()':

nCLC:93:36: error: invalid conversion from 'char*' to 'long int' [-fpermissive]

   configTime( cfg.getval("Timezone"), cfg.getval("NTP.server.1"), cfg.getval("NTP.server.2"), cfg.getval("NTP.server.3"));

                                    ^

In file included from sketch\nCLC.ino.cpp:1:0:

C:\Users\eric\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Arduino.h:278:17: error:   initializing argument 1 of 'void configTime(long int, int, const char*, const char*, const char*)' [-fpermissive]

 extern "C" void configTime(long timezone, int daylightOffset_sec,

                 ^

nCLC:93:64: error: invalid conversion from 'char*' to 'int' [-fpermissive]

   configTime( cfg.getval("Timezone"), cfg.getval("NTP.server.1"), cfg.getval("NTP.server.2"), cfg.getval("NTP.server.3"));

                                                                ^

In file included from sketch\nCLC.ino.cpp:1:0:

C:\Users\eric\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Arduino.h:278:17: error:   initializing argument 2 of 'void configTime(long int, int, const char*, const char*, const char*)' [-fpermissive]

 extern "C" void configTime(long timezone, int daylightOffset_sec,

                 ^

invalid conversion from 'char*' to 'long int' [-fpermissive]

how can i fix this and get it to compile?

**Comment by maarten-pennings** [comment]
Hi devicemodder (Eric), 


If I look at line 93 of the ino (where you report errors), I see 
```
  // nCLC.ino line 93
  configTime( cfg.getval("Timezone"), cfg.getval("NTP.server.1"), cfg.getval("NTP.server.2"), cfg.getval("NTP.server.3"));
```

The `cfg` object is from my library, the `getval()` returns a string
```
    // from Cfg.h line 212
    char * getval(const char * name);
```

These `getval` strings are passed to `configTime()`
```
/// time.cpp line 198
void configTime(const char* tz, const char* server1, const char* server2, const char* server3)
```
As you see, configTime gets char* as parameters

This comes from the following location
```
C:\Users\maarten\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266\time.cpp
```

You seem to end up in
```
C:\Users\eric\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Arduino.h:278:17
```
where you have a different `configTime`
```
initializing argument 1 of 'void configTime(long int, int, const char*, const char*, const char*)' [-fpermissive]
```
indeed a long int instead of a char*


I think you have a version mismatch somewhere.
Please check the following

(1) I just switched due to your submitted issue from Arduino IDE 1.8.13 to IDE 2.0.3. Both worked.
(2) You need to have the correct compiler for ESP8266. In board manager I have ESP8266 Boards (3.0.2) you seem to have an old one (2.4.0).
(3) I'm compiling for board: Generic ESP8266 module (as shown at the top of the ino file)
(4) You need supporting libraries Cfg and Nvm, see https://github.com/maarten-pennings/Cfg and https://github.com/maarten-pennings/Nvm

good luck,

Maarten

**Comment by maarten-pennings** [comment]
Long time no reaction, so I guess you have it compiling by now or are no longer interested.
I took the liberty to close the issue.

**Comment by devicemodder** [comment]
My bad on the no reaction. yes, got it working a while ago.
